### ISSUE TITLE
get_data() doesn't seem to be accessible from the console

### ISSUE THREAD

**Issue by fsdias** [DistanceDevelopment/readdst#11]
Running:
get_data("/media/fd/Dados/FilipeTrabalho/MonkeyBusiness/RondeHill/DISTANCE/StandingNestsIndividual/DistData.mdb")

Returns:

Error: could not find function "get_data"

(readdst is loaded of course)

**Comment by dill** [comment]
The `get_data()` function is used by `readdst` internally and is not 
intended for general use (you can access is by using 
`readdst:::get_data()` but I don't recommend that. The `$env$obs_table` 
element of the model specification objects returned by 
`convert_project()` will give the table that you want to feed to `ds()` 
or `ddf()`, that will be after the chosen data filters (e.g. subset by 
species or strata) have been applied.

HTH

**Comment by fsdias** [comment]
Ok. I think it would be useful to have an equivalent function available for general use. I'll open a separate issue.
