### ISSUE TITLE
run_analysis() returns unclear output

### ISSUE THREAD

**Issue by fsdias** [DistanceDevelopment/readdst#12]
I'm working with a project that I can send you privately

I run this:
project1<-"/path/to_folder"
converted <- convert_project(project1)

and it worked as expected. Then I looked into "converted" to see what was inside:

> converted
>    ID                   Name
> 1   3                 80+10c
> 2   4                   75+9
> 3   5                   70+8
> 4   6               Defaults
> 5   7                   72+9
> 6   9            Uni+poly+70
> 7  10            Uni+coos+72
> 8  11             Uni+cos+70
> 9  12              Hn+cos+72
> 10 13              Hn+cos+70
> 11 14            Uni+poly+72
> 12 15              Hr+cos+70
> 13 16            Hn+Hpoly+72
> 14 17            Hn+Hpoly+70
> 15 18             Hr+poly+70
> 16 19              Hr+cos+72
> 17 20             Hr+poly+72
> 18 21 Defaults no truncation

It's unclear what "80+10c" (line 1) means. To find out I did:

analysis_1 <- run_analysis(converted[[1]], debug=TRUE)

analysis_1

Model name: 80+10c 
Call:
 mrds::ddf(dsmodel=~cds(key="hn",formula=~1,adj.series="cos",adj.order=NULL),meta.data=list(width=101,left=0),control=list(mono=TRUE, mono.strict=TRUE),method="ds",data=obs_table) 

It turns out it's a Half-normal with cos adjustments. This is weird since lines 9 and 10 report half-normal
with cos adjustments using the proper nomenclature.

Is this due to something the person who used Distance 6.0 did wrong? Or a bug?

**Comment by dill** [comment]
The "Name" column just displays the name that has been given to that 
model in Distance. That's free text entry to relies on the user to input 
something that is intelligible by someone else.

HTH

**Comment by fsdias** [comment]
Thanks. It would be good to add this information to the help file
