### ISSUE TITLE
Add a function for retrieving observation data (and maybe segment data)

### ISSUE THREAD

**Issue by fsdias** [DistanceDevelopment/readdst#13]
I think it would be useful to have a function for retrieving observation data from a Distance project. A user that receives a Distance project may just want to retrieve the data and replicate the analysis independently. A function for retrieving segment data would also be useful.

**Comment by dill** [comment]
As of 5149159, `get_data` is exported for users to use. It returns a "flatfile" compatible `data.frame` so the results should be usable with `Distance`.

**Comment by dill** [comment]
As of 8b9245c, you can also use `unflatfile` to get the resulting flatfile data into shape for `mrds`.
