### ISSUE TITLE
Add more information to the output of "convert_project"

### ISSUE THREAD

**Issue by fsdias** [DistanceDevelopment/readdst#14]
Currently this command:

convert_project(project)

Generates:

ID                      Name
1   1             FI - Petersen
2   2              FI - MR dist
3   3 FI - MR dist+size+sex+exp
4   4      ds (single platform)
5   5                     trial
6   6                     io.fi
7   7                     io.pi
8   8            test intervals
9   9           FI - Petersen 1
10 10           FI - Petersen 2

Since "Name" can be uninformative as it's given by the user in Distance 6/7, I would suggest adding two more columns: 

Detection function - which would state something link hn+cos(2,3)
Truncation distance - eg 70

**Comment by dill** [comment]
I think it's definitely sensible to include more information here, 
though exactly what that is I need to think about a little more. For 
example in the examples you show, it would be useful to know the 
"Distance engine" used (in this case all MRDS), the model not only for 
the detection function but also for the mark-recapture part of the model 
(for these models at least) and other data filters applied.

At the moment this relies on the Distance user giving good labels, which 
I agree can be problematic.

In the meantime, you may or may not already know you can do

converted <- convert_project(project)
converted[[1]]

which will print details for that model, including the exact ddf call.

**Comment by fsdias** [comment]
Thanks for the tip.

I'm not familiar of with mark-recapture models but for regular distance sampling the list you wrote seems ok.
