### ISSUE TITLE
Missing vignette in package

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/readdst#37]
Version 0.0.5 installed 30May has no vignette (that I can see), even though repo has a vignette.  Was that deliberate--is the old vignette from 2016 out of date?  or just a build oversight?

**Comment by dill** [comment]
Is this as build with R CMD BUILD or some other mechanism?

**Comment by erex** [comment]
Sorry, I don't know the answer to that.  I don't know what devtools:::install_github() does.

**Comment by erex** [comment]
I believe `install_github()` used R CMD INSTALL rather than R CMD BUILD:

```
In R CMD INSTALL
"C:/PROGRA~1/R/R-35~1.0/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/eric/AppData/Local/Temp/RtmpEj4xCu/devtools24747145170f/DistanceDevelopment-readdst-d060267"  \
  --library="C:/Users/eric/Documents/R/win-library/3.5" --install-tests
```

What is not produced is an entry in the table of contents for package help, making it difficult for users to find said vignette.  Here is the table of contents for DSsim:

![image](https://user-images.githubusercontent.com/330744/40962752-5681b0d6-689e-11e8-9bd4-3e36be34152d.png)

**Comment by dill** [comment]
84af359 should fix this (at least using `R CMD BUILD` then `R CMD INSTALL` seemed to do the right thing. Eager to know if this works for you using `install_github()`.

![screen shot 2018-06-05 at 11 18 04](https://user-images.githubusercontent.com/1953/40970407-655d2d74-68b2-11e8-833a-3d7c73f1a7dc.png)

**Comment by erex** [comment]
No luck with `install_github()` either in RStudio
![image](https://user-images.githubusercontent.com/330744/40974018-293e2346-68be-11e8-816f-c8e4bba0f98c.png)

on with just R
![image](https://user-images.githubusercontent.com/330744/40974058-44c6a21e-68be-11e8-9ca1-882bffc7e1ef.png)

**Comment by dill** [comment]
install_github(build_vignettes=TRUE) might solve this?

**Comment by erex** [comment]
Thanks for reading the documentation for me.  
![image](https://user-images.githubusercontent.com/330744/40974494-a9ae30c4-68bf-11e8-95aa-4adb22b9a056.png)
