### ISSUE TITLE
Vignette incorrect

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/readdst#42]
KS test stats in plot are wrong because gof object structure has changed

I think amakihi is still incorrect

**Comment by erex** [comment]
I think I fixed the stratify KS test business via [a29ea13](https://github.com/DistanceDevelopment/readdst/commit/a29ea13a52a0cbd58652f7b50f2755ab06e6cbd6)

The amakihi data technically doesn't do anything incorrect in the vignette, because it only gets converted, but does not do anything after the conversion, so the analysis (in Windows) is not recognised as incorrect.

**Comment by dill** [comment]
Great, thanks. Will look into amakihi in the relevant thread here and close this issue.
