### ISSUE TITLE
Error message I can't translate

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/readdst#46]
New session running 32-bit R 3.6.1
```
> library(readdst) 
> library(RODBC) 
> proj <- "C:\\Users\\erexs\\Documents\\My Distance Projects\\sara\\Campanha Nereide 2019 2.0" 
> problem <- convert_project(project = proj) 
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
```

Running debug on `convert_project` produces:
```
debug: R_analyses <- dlply(analyses, .(ID), make_analysis, model_definitions, 
    data_filters, data = data, transect = transect)
Browse[2]> n
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
```

Zip file containing Distance project is attached.
[Análise Campanha Nereide 2019 2.0.zip](https://github.com/DistanceDevelopment/readdst/files/3563550/Analise.Campanha.Nereide.2019.2.0.zip)

Distance project browser contents looked like this when I was trying to convert:
![image](https://user-images.githubusercontent.com/330744/64077489-df191800-ccc8-11e9-8f1e-1d57bd418644.png)

**Comment by dill** [comment]
4a93ab2 should handle is issue.

**Comment by erex** [comment]
yes, complaint on that Distance project has gone away:
```
> hey_dave <- convert_project(project)
> str(hey_dave)
List of 11
```
