### ISSUE TITLE
Error installing: lazy loading failed for package ‘readdst’

### ISSUE THREAD

**Issue by NatureHeritage** [DistanceDevelopment/readdst#47]
I tried to install 'readrst' but get ERROR: lazy loading failed for package ‘readdst’

remotes::install_github("dill/readdst")
Downloading GitHub repo dill/readdst@HEAD
✓  checking for file ‘/private/var/folders/zl/9w03906d6jq43xnzbgl232280000gn/T/RtmpjTuBYp/remotes6783ea93693/DistanceDevelopment-readdst-b93e7fb/DESCRIPTION’ ...
─  preparing ‘readdst’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘readdst_0.0.6.tar.gz’
   
* installing *source* package ‘readdst’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘RODBC’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘readdst’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/readdst’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/zl/9w03906d6jq43xnzbgl232280000gn/T//RtmpjTuBYp/file678573e0d08/readdst_0.0.6.tar.gz’ had non-zero exit status
>

**Comment by dill** [comment]
Sorry to hear you're having problems, it looks like there's an issue finding the `RODBC` package. You could try

```r
remotes::install_github("DistanceDevelopment/readdst", dependencies=TRUE)
```

or try

```r
install.packages("RODBC")
remotes::install_github("DistanceDevelopment/readdst")
```

Hope that helps!

**Comment by NatureHeritage** [comment]
Thanks a lot for this VERY FAST reply!

The first option did not work
The second option worked perfectly!

Thanks!

With best regards

Stephan

**Comment by dill** [comment]
No worries. Glad to hear it! :)
